name: build module artifacts

#on:
#  schedule:
#    - cron: '30 3 * * 2,6'
#  pull_request:
#    branches:
#      - master

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "OpenWrt version"
        type: string
        required: true
        default: "23.05.3"
      openwrt_arch:
        description: "OpenWrt arch"
        type: string
        required: true
        default: "mips_24kc"
      openwrt_target:
        description: "OpenWrt target"
        type: string
        required: true
        default: "ath79"
      openwrt_subtarget:
        description: "OpenWrt subtarget"
        type: string
        required: true
        default: "generic"
      openwrt_vermagic:
        description: "OpenWrt vermagic"
        type: string
        required: true
        default: "auto"
      openwrt_snapshot_ref:
        description: "OpenWrt snapshot git ref"
        type: string
        required: false
        default: "main"

jobs:
  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch }} :: ${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }} amneziawg build"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_env:
          - tag: ${{ inputs.openwrt_version || vars.DEFAULT_OPENWRT_VERSION }}
            pkgarch: ${{ inputs.openwrt_arch || vars.DEFAULT_OPENWRT_ARCH }}
            target: ${{ inputs.openwrt_target || vars.DEFAULT_OPENWRT_TARGET }}
            subtarget: ${{ inputs.openwrt_subtarget || vars.DEFAULT_OPENWRT_SUBTARGET }}
            vermagic: ${{ inputs.openwrt_vermagic || vars.DEFAULT_OPENWRT_VERMAGIC }}
            snapshot_ref: ${{ inputs.openwrt_snapshot_ref || 'main' }}

    env:
      OPENWRT_RELEASE: ${{ matrix.build_env.tag }}
      OPENWRT_ARCH: ${{ matrix.build_env.pkgarch }}
      OPENWRT_TARGET: ${{ matrix.build_env.target }}
      OPENWRT_SUBTARGET: ${{ matrix.build_env.subtarget }}
      OPENWRT_VERMAGIC: ${{ matrix.build_env.vermagic }}
      OPENWRT_SNAPSHOT_REF: ${{ matrix.build_env.snapshot_ref }}

    steps:
      - name: checkout amneziawg-openwrt
        uses: actions/checkout@v4
        with:
          path: amneziawg-openwrt
          fetch-depth: 0

      - name: checkout openwrt (release)
        uses: actions/checkout@v4
        if: ${{ matrix.build_env.tag != 'snapshot' }}
        with:
          path: openwrt
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: checkout openwrt (snapshot)
        uses: actions/checkout@v4
        if: ${{ matrix.build_env.tag == 'snapshot' }}
        with:
          path: openwrt
          repository: openwrt/openwrt
          ref: ${{ matrix.build_env.snapshot_ref }}
          fetch-depth: 0

      - name: checkout usign
        uses: actions/checkout@v4
        with:
          path: usign
          repository: openwrt/usign
          fetch-depth: 0

      - name: build usign
        id: build-usign
        run: |
          set -x
          cd usign
          mkdir build
          cd build
          cmake ..
          make -j
          echo "$(pwd)" >> $GITHUB_PATH

      - name: restore cached tools and kernel
        id: cache-tools-kernel-restore
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          key: ${{ runner.os }}-openwrt-cache-toolchain-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch }}-${{ matrix.build_env.target }}-${{ matrix.build_env.subtarget }}
          restore-keys: |
            ${{ runner.os }}-openwrt-cache-tools-kernel-${{ matrix.build_env.pkgarch }}-
          path: |
            openwrt/.config
            openwrt/.config.old
            openwrt/feeds.conf
            openwrt/bin/**
            openwrt/build_dir/**
            openwrt/dl/**
            openwrt/feeds/**
            openwrt/package/**
            openwrt/staging_dir/**
            openwrt/tmp/**

      - name: build amneziawg
        id: build-amneziawg
        run: |
          set -x
          cd amneziawg-openwrt
          make show-env
          make export-env >> $GITHUB_OUTPUT
          time -p make build-amneziawg
          make prepare-artifacts

      - name: create feed archive
        id: create-feed-archive
        run: |
          set -x
          cd amneziawg-openwrt
          usign -G -s test.sec -p test.pub
          FEED_SEC_KEY=$(pwd)/test.sec FEED_PUB_KEY=$(pwd)/test.pub make create-feed-archive
          cp test.sec ../awgrelease/test.sec-${{ steps.build-amneziawg.outputs.version_str }}-openwrt-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}
          cp test.pub ../awgrelease/test.pub-${{ steps.build-amneziawg.outputs.version_str }}-openwrt-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}

      - name: upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-${{ steps.build-amneziawg.outputs.version_str }}-openwrt-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}
          path: |
            awgrelease/*.gz
            awgrelease/test.pub-*
            awgrelease/test.sec-*
